[package]
org = "shammi"
name = "persist_test"
version = "0.1.0"
distribution = "2201.6.0"

[build-options]
observabilityIncluded = true

[persist]
datastore = "mysql"
module = "persist_test.store"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.0.0"
